"""Data models exposed by the minimal TDX code-table protocol."""

from __future__ import annotations

from importlib import import_module

_EXPORT_MODULES = {
    "AuctionProcessRecord": ".auction",
    "AuctionProcessSeries": ".auction",
    "CapitalChangeBlock": ".corporate",
    "CapitalChangeRecord": ".corporate",
    "CategoryQuote": ".quote",
    "CategoryQuotePage": ".quote",
    "ChartSamplingSeries": ".chart_sampling",
    "ExplicitQuote": ".quote",
    "FileContentChunk": ".resource",
    "FileMeta": ".resource",
    "FinanceInfoBlock": ".finance",
    "FinanceInfoRecord": ".finance",
    "HandshakeInfo": ".session",
    "HeartbeatAck": ".session",
    "HistoricalIntradayPoint": ".intraday",
    "HistoricalIntradaySeries": ".intraday",
    "IndexInfoOrder": ".index",
    "IndexInfoSnapshot": ".index",
    "IndexMomentumSeries": ".index",
    "MacAuctionPage": ".mac_auction",
    "MacAuctionItem": ".mac_auction",
    "MacBelongBoardItem": ".mac_symbol_belong_board",
    "MacBoardListPage": ".mac_board",
    "MacBoardListItem": ".mac_board",
    "MacBoardMemberItem": ".mac_board_members",
    "MacBoardMemberQuoteDynamicItem": ".mac_board_members",
    "MacBoardMemberQuoteItem": ".mac_board_members",
    "MacBoardMembersDynamicPage": ".mac_board_members",
    "MacBoardMembersPage": ".mac_board_members",
    "MacBoardMembersQuotesPage": ".mac_board_members",
    "MacDynamicFieldDef": ".mac_symbol_quotes",
    "MacFileDownloadChunk": ".mac_file",
    "MacFileListMeta": ".mac_file",
    "MacKlineOffset": ".mac_kline_offset",
    "MacMarketMonitorItem": ".mac_market_monitor",
    "MacMarketMonitorPage": ".mac_market_monitor",
    "MacQuoteChartItem": ".mac_quotes",
    "MacQuotesSnapshot": ".mac_quotes",
    "MacServerInfo": ".mac_server_info",
    "MacSymbolBar": ".mac_symbol_bars",
    "MacSymbolBarsPage": ".mac_symbol_bars",
    "MacSymbolBelongBoardList": ".mac_symbol_belong_board",
    "MacSymbolInfo": ".mac_symbol_info",
    "MacSymbolQuoteItem": ".mac_symbol_quotes",
    "MacSymbolQuotesPage": ".mac_symbol_quotes",
    "MacTickChartDay": ".mac_tick_charts",
    "MacTickChartItem": ".mac_tick_charts",
    "MacTickChartsPage": ".mac_tick_charts",
    "MacTradingSession": ".mac_server_info",
    "MacTransactionItem": ".mac_transactions",
    "MacTransactionsPage": ".mac_transactions",
    "IntradaySubchartPoint": ".subchart",
    "IntradaySubchartSeries": ".subchart",
    "KlineBar": ".kline",
    "KlineSeries": ".kline",
    "LegacyQuote": ".quote",
    "PriceLimitRecord": ".quote",
    "QuoteLevel": ".quote",
    "QuoteRefreshBatch": ".quote",
    "QuoteRefreshCursor": ".quote",
    "QuoteRefreshRecord": ".quote",
    "RecentHistoricalIntradayPoint": ".intraday",
    "RecentHistoricalIntradaySeries": ".intraday",
    "SecurityCode": ".security",
    "SecurityCodeOld": ".security_old",
    "SecurityListOldPage": ".security_old",
    "ServerInfo": ".server_info",
    "TodayIntradayPoint": ".intraday",
    "TodayIntradaySeries": ".intraday",
    "TopBoardItem": ".board",
    "TopBoardPage": ".board",
    "TradeDetailRecord": ".trade",
    "TradeDetailSeries": ".trade",
    "UnusualPage": ".unusual",
    "UnusualRecord": ".unusual",
    "VolumeProfileItem": ".volume_profile",
    "VolumeProfileLevel": ".volume_profile",
    "VolumeProfileSnapshot": ".volume_profile",
}

__all__ = [
    "AuctionProcessRecord",
    "AuctionProcessSeries",
    "CapitalChangeBlock",
    "CapitalChangeRecord",
    "ChartSamplingSeries",
    "FinanceInfoBlock",
    "FinanceInfoRecord",
    "HandshakeInfo",
    "HeartbeatAck",
    "HistoricalIntradayPoint",
    "HistoricalIntradaySeries",
    "IndexInfoOrder",
    "IndexInfoSnapshot",
    "IndexMomentumSeries",
    "RecentHistoricalIntradayPoint",
    "RecentHistoricalIntradaySeries",
    "SecurityCodeOld",
    "SecurityListOldPage",
    "ServerInfo",
    "TodayIntradayPoint",
    "TodayIntradaySeries",
    "TopBoardItem",
    "TopBoardPage",
    "IntradaySubchartPoint",
    "IntradaySubchartSeries",
    "KlineBar",
    "KlineSeries",
    "CategoryQuote",
    "CategoryQuotePage",
    "ExplicitQuote",
    "FileContentChunk",
    "LegacyQuote",
    "PriceLimitRecord",
    "QuoteLevel",
    "QuoteRefreshBatch",
    "QuoteRefreshCursor",
    "QuoteRefreshRecord",
    "SecurityCode",
    "TradeDetailRecord",
    "TradeDetailSeries",
    "UnusualPage",
    "UnusualRecord",
    "VolumeProfileItem",
    "VolumeProfileLevel",
    "VolumeProfileSnapshot",
    "FileMeta",
    "MacAuctionPage",
    "MacBelongBoardItem",
    "MacBoardListItem",
    "MacBoardListPage",
    "MacBoardMemberItem",
    "MacBoardMemberQuoteDynamicItem",
    "MacBoardMemberQuoteItem",
    "MacBoardMembersDynamicPage",
    "MacBoardMembersPage",
    "MacBoardMembersQuotesPage",
    "MacDynamicFieldDef",
    "MacFileDownloadChunk",
    "MacFileListMeta",
    "MacKlineOffset",
    "MacMarketMonitorItem",
    "MacMarketMonitorPage",
    "MacQuoteChartItem",
    "MacQuotesSnapshot",
    "MacServerInfo",
    "MacSymbolBar",
    "MacSymbolBarsPage",
    "MacSymbolBelongBoardList",
    "MacSymbolInfo",
    "MacSymbolQuoteItem",
    "MacSymbolQuotesPage",
    "MacTickChartDay",
    "MacTickChartItem",
    "MacTickChartsPage",
    "MacTradingSession",
    "MacTransactionItem",
    "MacTransactionsPage",
]


def __getattr__(name: str):
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(__all__))
