"""Provider-owned command registry metadata facts."""

COMMAND_METADATA_ITEMS: tuple[tuple[str, str, str, bool, str], ...] = (
    (
        "exchange_announcement",
        "session",
        "exchange_announcement",
        False,
        "gotdx proto/server.go（KMSG_EXCHANGEANNOUNCE=0x0002 交易所公告）",
    ),
    ("heartbeat", "session", "heartbeat", True, "0x0004-心跳保活接口.md"),
    (
        "announcement",
        "session",
        "announcement",
        False,
        "gotdx proto/server.go（KMSG_ANNOUNCEMENT=0x000a 服务商公告）",
    ),
    ("handshake", "session", "handshake", True, "0x000d-连接握手接口.md"),
    ("capital_changes", "corporate", "capital_changes", False, "0x000f-股本变迁查询接口.md"),
    ("finance_info", "finance", "info", False, "0x0010-财务信息批量查询&下发接口.md"),
    ("server_info", "session", "server_info", False, "0x0015-服务器信息接口.md"),
    ("file_meta", "resources", "file_meta", False, "gotdx proto/get_file.go（0x02c5 文件元信息）"),
    ("security_list", "codes", "list", True, "0x044d-代码表分页接口.md"),
    ("security_count", "codes", "count", True, "0x044e-代码数量接口.md"),
    ("security_list_old", "codes", "list_old", False, "0x0450-旧版代码表分页接口.md"),
    ("price_limits", "quotes", "price_limits", False, "0x0452-特殊品种涨跌停限制表接口.md"),
    ("volume_profile", "quotes", "volume_profile", False, "0x051a-成交分布接口.md"),
    ("intraday_subchart", "intraday", "subchart", False, "0x051b-个股分时副图数据接口.md"),
    ("index_momentum", "index", "momentum", False, "0x051c-指数动量接口.md"),
    ("index_info", "index", "info", False, "0x051d-指数概况接口.md"),
    (
        "klines_0523",
        "bars",
        "get_0523",
        False,
        "gotdx proto/get_security_bars.go（NewGetSecurityBars 0x0523，区别 0x052d 偏移版）",
    ),
    ("klines", "bars", "get", False, "0x052d-K线周期数据接口.md"),
    ("today_intraday", "intraday", "today", False, "0x0537-个股当前日分时图接口.md"),
    ("legacy_quotes", "quotes", "legacy", False, "0x053e-旧版批量行情快照接口.md"),
    ("top_board", "market", "top_board", False, "0x053f-排行榜接口.md"),
    ("refresh_quotes", "quotes", "refresh", False, "0x0547-行情增量刷新推送接口.md"),
    ("category_quotes", "quotes", "category", False, "0x054b-分类行情列表分页接口.md"),
    ("explicit_quotes", "quotes", "explicit", False, "0x054c-显式代码批量行情快照接口.md"),
    ("unusual", "market", "unusual", False, "0x0563-主力监控异动接口.md"),
    ("auction_process", "auction", "process", False, "0x056a-集合竞价明细接口.md"),
    ("file_content", "resources", "download_chunk", False, "0x06b9-文件资源下载接口.md"),
    ("historical_intraday", "intraday", "historical", False, "0x0fb4-历史分时数据接口.md"),
    (
        "historical_trades_basic",
        "trades",
        "historical_basic",
        False,
        "gotdx proto/get_history_transaction_data.go（0x0fb5 基础版，区别 0x0fc6）",
    ),
    ("today_trades", "trades", "today", False, "0x0fc5-当日成交明细分页接口.md"),
    ("historical_trades", "trades", "historical", False, "0x0fc6-历史成交明细增强分页接口.md"),
    (
        "chart_sampling",
        "intraday",
        "chart_sampling",
        False,
        "0x0fd1-抽样图数据接口.md",
    ),
    (
        "recent_historical_intraday",
        "intraday",
        "recent_historical",
        False,
        "0x0feb-近期历史分时图接口.md",
    ),
    # MAC 余族（gotdx proto/mac_*.go；无官方接口文档，document 指向 gotdx 源）。
    # 条目顺序与 _command_codes.COMMAND_CODE_ITEMS 严格一致（registry 测试钉住）。
    ("mac_server_info", "mac", "server_info", False, "gotdx proto/mac_server_info.go"),
    ("mac_file_list", "mac", "file_list", False, "gotdx proto/mac_file.go（MACFileList）"),
    (
        "mac_file_download",
        "mac",
        "file_download",
        False,
        "gotdx proto/mac_file.go（MACFileDownload）",
    ),
    ("mac_capital_flow", "mac", "capital_flow", False, "0x1218-MAC资金流向接口.md"),
    (
        "mac_symbol_belong_board",
        "mac",
        "symbol_belong_board",
        False,
        "gotdx proto/mac_symbol_belong_board.go（0x1218 同码，query=Stock_GLHQ）",
    ),
    ("mac_symbol_info", "mac", "symbol_info", False, "gotdx proto/mac_symbol_info.go"),
    ("mac_symbol_quotes", "mac", "symbol_quotes", False, "gotdx proto/mac_symbol_quotes.go"),
    ("mac_board_members", "mac", "board_members", False, "gotdx proto/mac_board_members*.go"),
    ("mac_quotes", "mac", "quotes", False, "gotdx proto/mac_quotes.go（含 with_date 变体）"),
    ("mac_symbol_bars", "mac", "symbol_bars", False, "gotdx proto/mac_symbol_bars.go"),
    (
        "mac_transactions",
        "mac",
        "transactions",
        False,
        "gotdx proto/mac_transactions.go（含 with_date 变体）",
    ),
    (
        "mac_board_list",
        "mac",
        "board_list",
        False,
        "gotdx proto/mac_board.go（board_count/board_list 同码同请求）",
    ),
    ("mac_market_monitor", "mac", "market_monitor", False, "gotdx proto/mac_market_monitor.go"),
    ("mac_auction", "mac", "auction", False, "gotdx proto/mac_auction.go"),
    ("mac_tick_charts", "mac", "tick_charts", False, "gotdx proto/mac_tick_charts.go"),
    ("mac_kline_offset", "mac", "kline_offset", False, "gotdx proto/mac_kline_offset.go"),
)

__all__ = ["COMMAND_METADATA_ITEMS"]
